/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientId = IDL.Nat;
export const TaskId = IDL.Nat;
export const Client = IDL.Record({
  'id' : ClientId,
  'contactInfo' : IDL.Text,
  'projects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'clientId' : ClientId,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'deadline' : IDL.Opt(IDL.Int),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [ClientId],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, ClientId, IDL.Opt(IDL.Int)],
      [TaskId],
      [],
    ),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
  'getTasksByClient' : IDL.Func([ClientId], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func(
      [ClientId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientId = IDL.Nat;
  const TaskId = IDL.Nat;
  const Client = IDL.Record({
    'id' : ClientId,
    'contactInfo' : IDL.Text,
    'projects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'clientId' : ClientId,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'deadline' : IDL.Opt(IDL.Int),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [ClientId],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, ClientId, IDL.Opt(IDL.Int)],
        [TaskId],
        [],
      ),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
    'getTasksByClient' : IDL.Func([ClientId], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func(
        [ClientId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };