/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PartialAssigneeInput = IDL.Record({
  'name' : IDL.Text,
  'captain' : IDL.Opt(IDL.Text),
});
export const AssigneeId = IDL.Nat;
export const PartialClientInput = IDL.Record({
  'pan' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'gstin' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
});
export const ClientId = IDL.Nat;
export const TaskId = IDL.Nat;
export const PartialTodoInput = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Opt(IDL.Text),
  'priority' : IDL.Opt(IDL.Nat),
});
export const TodoId = IDL.Nat;
export const Assignee = IDL.Record({
  'id' : AssigneeId,
  'name' : IDL.Text,
  'captain' : IDL.Opt(IDL.Text),
});
export const Client = IDL.Record({
  'id' : ClientId,
  'pan' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'gstin' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : IDL.Opt(IDL.Text),
  'subCategory' : IDL.Text,
  'paymentStatus' : IDL.Opt(IDL.Text),
  'completionDate' : IDL.Opt(IDL.Int),
  'clientName' : IDL.Text,
  'assignmentDate' : IDL.Opt(IDL.Int),
  'bill' : IDL.Opt(IDL.Float64),
  'advanceReceived' : IDL.Opt(IDL.Float64),
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Int),
  'comment' : IDL.Opt(IDL.Text),
  'outstandingAmount' : IDL.Opt(IDL.Float64),
  'taskCategory' : IDL.Text,
  'assignedName' : IDL.Opt(IDL.Text),
});
export const TaskWithCaptain = IDL.Record({
  'captainName' : IDL.Opt(IDL.Text),
  'task' : Task,
});
export const Todo = IDL.Record({
  'id' : TodoId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'priority' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssignee' : IDL.Func([PartialAssigneeInput], [AssigneeId], []),
  'createClient' : IDL.Func([PartialClientInput], [ClientId], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TaskId], []),
  'createTodo' : IDL.Func([PartialTodoInput], [TodoId], []),
  'deleteAssignee' : IDL.Func([AssigneeId], [], []),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'deleteTodo' : IDL.Func([TodoId], [], []),
  'getAllAssignees' : IDL.Func([], [IDL.Vec(Assignee)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTasksWithCaptain' : IDL.Func(
      [],
      [IDL.Vec(TaskWithCaptain)],
      ['query'],
    ),
  'getAllTodos' : IDL.Func([], [IDL.Vec(Todo)], ['query']),
  'getAssignee' : IDL.Func([AssigneeId], [IDL.Opt(Assignee)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
  'getTodo' : IDL.Func([TodoId], [IDL.Opt(Todo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAssignee' : IDL.Func([AssigneeId, PartialAssigneeInput], [], []),
  'updateClient' : IDL.Func([ClientId, PartialClientInput], [], []),
  'updateTask' : IDL.Func(
      [
        TaskId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateTodo' : IDL.Func([TodoId, PartialTodoInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PartialAssigneeInput = IDL.Record({
    'name' : IDL.Text,
    'captain' : IDL.Opt(IDL.Text),
  });
  const AssigneeId = IDL.Nat;
  const PartialClientInput = IDL.Record({
    'pan' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'gstin' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
  });
  const ClientId = IDL.Nat;
  const TaskId = IDL.Nat;
  const PartialTodoInput = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Opt(IDL.Text),
    'priority' : IDL.Opt(IDL.Nat),
  });
  const TodoId = IDL.Nat;
  const Assignee = IDL.Record({
    'id' : AssigneeId,
    'name' : IDL.Text,
    'captain' : IDL.Opt(IDL.Text),
  });
  const Client = IDL.Record({
    'id' : ClientId,
    'pan' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'gstin' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : IDL.Opt(IDL.Text),
    'subCategory' : IDL.Text,
    'paymentStatus' : IDL.Opt(IDL.Text),
    'completionDate' : IDL.Opt(IDL.Int),
    'clientName' : IDL.Text,
    'assignmentDate' : IDL.Opt(IDL.Int),
    'bill' : IDL.Opt(IDL.Float64),
    'advanceReceived' : IDL.Opt(IDL.Float64),
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Int),
    'comment' : IDL.Opt(IDL.Text),
    'outstandingAmount' : IDL.Opt(IDL.Float64),
    'taskCategory' : IDL.Text,
    'assignedName' : IDL.Opt(IDL.Text),
  });
  const TaskWithCaptain = IDL.Record({
    'captainName' : IDL.Opt(IDL.Text),
    'task' : Task,
  });
  const Todo = IDL.Record({
    'id' : TodoId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'priority' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssignee' : IDL.Func([PartialAssigneeInput], [AssigneeId], []),
    'createClient' : IDL.Func([PartialClientInput], [ClientId], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TaskId], []),
    'createTodo' : IDL.Func([PartialTodoInput], [TodoId], []),
    'deleteAssignee' : IDL.Func([AssigneeId], [], []),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'deleteTodo' : IDL.Func([TodoId], [], []),
    'getAllAssignees' : IDL.Func([], [IDL.Vec(Assignee)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTasksWithCaptain' : IDL.Func(
        [],
        [IDL.Vec(TaskWithCaptain)],
        ['query'],
      ),
    'getAllTodos' : IDL.Func([], [IDL.Vec(Todo)], ['query']),
    'getAssignee' : IDL.Func([AssigneeId], [IDL.Opt(Assignee)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
    'getTodo' : IDL.Func([TodoId], [IDL.Opt(Todo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAssignee' : IDL.Func([AssigneeId, PartialAssigneeInput], [], []),
    'updateClient' : IDL.Func([ClientId, PartialClientInput], [], []),
    'updateTask' : IDL.Func(
        [
          TaskId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateTodo' : IDL.Func([TodoId, PartialTodoInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };