/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PartialAssigneeInput = IDL.Record({
  'name' : IDL.Text,
  'captain' : IDL.Opt(IDL.Text),
});
export const AssigneeId = IDL.Nat;
export const PartialClientInput = IDL.Record({
  'pan' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'gstin' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
});
export const ClientId = IDL.Nat;
export const TaskInput = IDL.Record({
  'status' : IDL.Opt(IDL.Text),
  'subCategory' : IDL.Text,
  'paymentStatus' : IDL.Opt(IDL.Text),
  'completionDate' : IDL.Opt(IDL.Int),
  'clientName' : IDL.Text,
  'assignmentDate' : IDL.Opt(IDL.Int),
  'bill' : IDL.Opt(IDL.Float64),
  'advanceReceived' : IDL.Opt(IDL.Float64),
  'dueDate' : IDL.Opt(IDL.Int),
  'comment' : IDL.Opt(IDL.Text),
  'outstandingAmount' : IDL.Opt(IDL.Float64),
  'taskCategory' : IDL.Text,
  'assignedName' : IDL.Opt(IDL.Text),
});
export const TaskId = IDL.Nat;
export const PartialTaskUpdate = IDL.Record({
  'status' : IDL.Opt(IDL.Text),
  'subCategory' : IDL.Opt(IDL.Text),
  'paymentStatus' : IDL.Opt(IDL.Text),
  'completionDate' : IDL.Opt(IDL.Int),
  'clientName' : IDL.Opt(IDL.Text),
  'assignmentDate' : IDL.Opt(IDL.Int),
  'bill' : IDL.Opt(IDL.Float64),
  'advanceReceived' : IDL.Opt(IDL.Float64),
  'dueDate' : IDL.Opt(IDL.Int),
  'comment' : IDL.Opt(IDL.Text),
  'outstandingAmount' : IDL.Opt(IDL.Float64),
  'taskCategory' : IDL.Opt(IDL.Text),
  'assignedName' : IDL.Opt(IDL.Text),
});
export const Assignee = IDL.Record({
  'id' : AssigneeId,
  'name' : IDL.Text,
  'captain' : IDL.Opt(IDL.Text),
});
export const Client = IDL.Record({
  'id' : ClientId,
  'pan' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'gstin' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : IDL.Opt(IDL.Text),
  'subCategory' : IDL.Text,
  'paymentStatus' : IDL.Opt(IDL.Text),
  'completionDate' : IDL.Opt(IDL.Int),
  'clientName' : IDL.Text,
  'assignmentDate' : IDL.Opt(IDL.Int),
  'bill' : IDL.Opt(IDL.Float64),
  'advanceReceived' : IDL.Opt(IDL.Float64),
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Int),
  'comment' : IDL.Opt(IDL.Text),
  'outstandingAmount' : IDL.Opt(IDL.Float64),
  'taskCategory' : IDL.Text,
  'assignedName' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkCreateAssignees' : IDL.Func(
      [IDL.Vec(PartialAssigneeInput)],
      [IDL.Vec(AssigneeId)],
      [],
    ),
  'bulkCreateClients' : IDL.Func(
      [IDL.Vec(PartialClientInput)],
      [IDL.Vec(ClientId)],
      [],
    ),
  'bulkCreateTasks' : IDL.Func([IDL.Vec(TaskInput)], [IDL.Vec(TaskId)], []),
  'bulkDeleteAssignees' : IDL.Func([IDL.Vec(AssigneeId)], [], []),
  'bulkDeleteClients' : IDL.Func([IDL.Vec(ClientId)], [], []),
  'bulkDeleteTasks' : IDL.Func([IDL.Vec(TaskId)], [], []),
  'bulkUpdateTasks' : IDL.Func(
      [IDL.Vec(IDL.Tuple(TaskId, PartialTaskUpdate))],
      [],
      [],
    ),
  'createAssignee' : IDL.Func([PartialAssigneeInput], [AssigneeId], []),
  'createClient' : IDL.Func([PartialClientInput], [ClientId], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TaskId], []),
  'deleteAssignee' : IDL.Func([AssigneeId], [], []),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getAllAssignees' : IDL.Func([], [IDL.Vec(Assignee)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAssignee' : IDL.Func([AssigneeId], [IDL.Opt(Assignee)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAssignee' : IDL.Func([AssigneeId, PartialAssigneeInput], [], []),
  'updateClient' : IDL.Func([ClientId, PartialClientInput], [], []),
  'updateTask' : IDL.Func(
      [
        TaskId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PartialAssigneeInput = IDL.Record({
    'name' : IDL.Text,
    'captain' : IDL.Opt(IDL.Text),
  });
  const AssigneeId = IDL.Nat;
  const PartialClientInput = IDL.Record({
    'pan' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'gstin' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
  });
  const ClientId = IDL.Nat;
  const TaskInput = IDL.Record({
    'status' : IDL.Opt(IDL.Text),
    'subCategory' : IDL.Text,
    'paymentStatus' : IDL.Opt(IDL.Text),
    'completionDate' : IDL.Opt(IDL.Int),
    'clientName' : IDL.Text,
    'assignmentDate' : IDL.Opt(IDL.Int),
    'bill' : IDL.Opt(IDL.Float64),
    'advanceReceived' : IDL.Opt(IDL.Float64),
    'dueDate' : IDL.Opt(IDL.Int),
    'comment' : IDL.Opt(IDL.Text),
    'outstandingAmount' : IDL.Opt(IDL.Float64),
    'taskCategory' : IDL.Text,
    'assignedName' : IDL.Opt(IDL.Text),
  });
  const TaskId = IDL.Nat;
  const PartialTaskUpdate = IDL.Record({
    'status' : IDL.Opt(IDL.Text),
    'subCategory' : IDL.Opt(IDL.Text),
    'paymentStatus' : IDL.Opt(IDL.Text),
    'completionDate' : IDL.Opt(IDL.Int),
    'clientName' : IDL.Opt(IDL.Text),
    'assignmentDate' : IDL.Opt(IDL.Int),
    'bill' : IDL.Opt(IDL.Float64),
    'advanceReceived' : IDL.Opt(IDL.Float64),
    'dueDate' : IDL.Opt(IDL.Int),
    'comment' : IDL.Opt(IDL.Text),
    'outstandingAmount' : IDL.Opt(IDL.Float64),
    'taskCategory' : IDL.Opt(IDL.Text),
    'assignedName' : IDL.Opt(IDL.Text),
  });
  const Assignee = IDL.Record({
    'id' : AssigneeId,
    'name' : IDL.Text,
    'captain' : IDL.Opt(IDL.Text),
  });
  const Client = IDL.Record({
    'id' : ClientId,
    'pan' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'gstin' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : IDL.Opt(IDL.Text),
    'subCategory' : IDL.Text,
    'paymentStatus' : IDL.Opt(IDL.Text),
    'completionDate' : IDL.Opt(IDL.Int),
    'clientName' : IDL.Text,
    'assignmentDate' : IDL.Opt(IDL.Int),
    'bill' : IDL.Opt(IDL.Float64),
    'advanceReceived' : IDL.Opt(IDL.Float64),
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Int),
    'comment' : IDL.Opt(IDL.Text),
    'outstandingAmount' : IDL.Opt(IDL.Float64),
    'taskCategory' : IDL.Text,
    'assignedName' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkCreateAssignees' : IDL.Func(
        [IDL.Vec(PartialAssigneeInput)],
        [IDL.Vec(AssigneeId)],
        [],
      ),
    'bulkCreateClients' : IDL.Func(
        [IDL.Vec(PartialClientInput)],
        [IDL.Vec(ClientId)],
        [],
      ),
    'bulkCreateTasks' : IDL.Func([IDL.Vec(TaskInput)], [IDL.Vec(TaskId)], []),
    'bulkDeleteAssignees' : IDL.Func([IDL.Vec(AssigneeId)], [], []),
    'bulkDeleteClients' : IDL.Func([IDL.Vec(ClientId)], [], []),
    'bulkDeleteTasks' : IDL.Func([IDL.Vec(TaskId)], [], []),
    'bulkUpdateTasks' : IDL.Func(
        [IDL.Vec(IDL.Tuple(TaskId, PartialTaskUpdate))],
        [],
        [],
      ),
    'createAssignee' : IDL.Func([PartialAssigneeInput], [AssigneeId], []),
    'createClient' : IDL.Func([PartialClientInput], [ClientId], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TaskId], []),
    'deleteAssignee' : IDL.Func([AssigneeId], [], []),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getAllAssignees' : IDL.Func([], [IDL.Vec(Assignee)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAssignee' : IDL.Func([AssigneeId], [IDL.Opt(Assignee)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAssignee' : IDL.Func([AssigneeId, PartialAssigneeInput], [], []),
    'updateClient' : IDL.Func([ClientId, PartialClientInput], [], []),
    'updateTask' : IDL.Func(
        [
          TaskId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };