/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'contactInfo' : string,
  'projects' : Array<string>,
  'name' : string,
  'timestamp' : bigint,
}
export type ClientId = bigint;
export interface PartialTaskUpdate {
  'status' : [] | [string],
  'subCategory' : [] | [string],
  'paymentStatus' : [] | [string],
  'completionDate' : [] | [bigint],
  'clientName' : [] | [string],
  'assignmentDate' : [] | [bigint],
  'bill' : [] | [number],
  'advanceReceived' : [] | [number],
  'dueDate' : [] | [bigint],
  'comment' : [] | [string],
  'outstandingAmount' : [] | [number],
  'taskCategory' : [] | [string],
  'assignedName' : [] | [string],
}
export interface Task {
  'id' : TaskId,
  'status' : [] | [string],
  'subCategory' : string,
  'paymentStatus' : [] | [string],
  'completionDate' : [] | [bigint],
  'clientName' : string,
  'assignmentDate' : [] | [bigint],
  'bill' : [] | [number],
  'advanceReceived' : [] | [number],
  'createdAt' : bigint,
  'dueDate' : [] | [bigint],
  'comment' : [] | [string],
  'outstandingAmount' : [] | [number],
  'taskCategory' : string,
  'assignedName' : [] | [string],
}
export type TaskId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkCreateTasks' : ActorMethod<
    [Array<[string, string, string]>],
    Array<TaskId>
  >,
  'bulkDeleteTasks' : ActorMethod<[Array<TaskId>], undefined>,
  'bulkUpdateTasks' : ActorMethod<
    [Array<[TaskId, PartialTaskUpdate]>],
    undefined
  >,
  'createClient' : ActorMethod<[string, string, Array<string>], ClientId>,
  'createTask' : ActorMethod<[string, string, string], TaskId>,
  'deleteClient' : ActorMethod<[ClientId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[ClientId], [] | [Client]>,
  'getTask' : ActorMethod<[TaskId], [] | [Task]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<
    [ClientId, string, string, Array<string>],
    undefined
  >,
  'updateTask' : ActorMethod<
    [
      TaskId,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];