/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaskInput {
    subCategory: string;
    clientName: string;
    taskCategory: string;
}
export interface PartialClientInput {
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
}
export interface PartialTaskUpdate {
    status?: string;
    subCategory?: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName?: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory?: string;
    assignedName?: string;
}
export type TaskId = bigint;
export interface Task {
    id: TaskId;
    status?: string;
    subCategory: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    createdAt: bigint;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory: string;
    assignedName?: string;
}
export interface Client {
    id: ClientId;
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
    timestamp: bigint;
}
export type ClientId = bigint;
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkCreateClients(clientInputs: Array<PartialClientInput>): Promise<Array<ClientId>>;
    bulkCreateTasks(taskInputs: Array<TaskInput>): Promise<Array<TaskId>>;
    bulkDeleteClients(clientIds: Array<ClientId>): Promise<void>;
    bulkDeleteTasks(taskIds: Array<TaskId>): Promise<void>;
    bulkUpdateTasks(taskUpdates: Array<[TaskId, PartialTaskUpdate]>): Promise<void>;
    createClient(client: PartialClientInput): Promise<ClientId>;
    createTask(clientName: string, taskCategory: string, subCategory: string): Promise<TaskId>;
    deleteClient(clientId: ClientId): Promise<void>;
    deleteTask(taskId: TaskId): Promise<void>;
    getAllClients(): Promise<Array<Client>>;
    getAllTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(clientId: ClientId): Promise<Client | null>;
    getTask(taskId: TaskId): Promise<Task | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClient(clientId: ClientId, client: PartialClientInput): Promise<void>;
    updateTask(taskId: TaskId, clientName: string, taskCategory: string, subCategory: string, status: string | null, comment: string | null, assignedName: string | null, dueDate: bigint | null, assignmentDate: bigint | null, completionDate: bigint | null, bill: number | null, advanceReceived: number | null, outstandingAmount: number | null, paymentStatus: string | null): Promise<void>;
}
import type { Client as _Client, ClientId as _ClientId, PartialClientInput as _PartialClientInput, PartialTaskUpdate as _PartialTaskUpdate, Task as _Task, TaskId as _TaskId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkCreateClients(arg0: Array<PartialClientInput>): Promise<Array<ClientId>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkCreateClients(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkCreateClients(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkCreateTasks(arg0: Array<TaskInput>): Promise<Array<TaskId>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkCreateTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkCreateTasks(arg0);
            return result;
        }
    }
    async bulkDeleteClients(arg0: Array<ClientId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteClients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteClients(arg0);
            return result;
        }
    }
    async bulkDeleteTasks(arg0: Array<TaskId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteTasks(arg0);
            return result;
        }
    }
    async bulkUpdateTasks(arg0: Array<[TaskId, PartialTaskUpdate]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateTasks(to_candid_vec_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateTasks(to_candid_vec_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createClient(arg0: PartialClientInput): Promise<ClientId> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(to_candid_PartialClientInput_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(to_candid_PartialClientInput_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: string): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: ClientId): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClient(arg0: ClientId, arg1: PartialClientInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, to_candid_PartialClientInput_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, to_candid_PartialClientInput_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string | null, arg6: string | null, arg7: bigint | null, arg8: bigint | null, arg9: bigint | null, arg10: number | null, arg11: number | null, arg12: number | null, arg13: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
}
function from_candid_Client_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : from_candid_Client_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClientId;
    pan: [] | [string];
    name: string;
    gstin: [] | [string];
    notes: [] | [string];
    timestamp: bigint;
}): {
    id: ClientId;
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        pan: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.pan)),
        name: value.name,
        gstin: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.gstin)),
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: [] | [string];
    subCategory: string;
    paymentStatus: [] | [string];
    completionDate: [] | [bigint];
    clientName: string;
    assignmentDate: [] | [bigint];
    bill: [] | [number];
    advanceReceived: [] | [number];
    createdAt: bigint;
    dueDate: [] | [bigint];
    comment: [] | [string];
    outstandingAmount: [] | [number];
    taskCategory: string;
    assignedName: [] | [string];
}): {
    id: TaskId;
    status?: string;
    subCategory: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    createdAt: bigint;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory: string;
    assignedName?: string;
} {
    return {
        id: value.id,
        status: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.status)),
        subCategory: value.subCategory,
        paymentStatus: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.paymentStatus)),
        completionDate: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.completionDate)),
        clientName: value.clientName,
        assignmentDate: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignmentDate)),
        bill: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bill)),
        advanceReceived: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.advanceReceived)),
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.dueDate)),
        comment: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.comment)),
        outstandingAmount: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.outstandingAmount)),
        taskCategory: value.taskCategory,
        assignedName: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.assignedName))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n15(_uploadFile, _downloadFile, x));
}
function to_candid_PartialClientInput_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialClientInput): _PartialClientInput {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_PartialTaskUpdate_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialTaskUpdate): _PartialTaskUpdate {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
}): {
    pan: [] | [string];
    name: string;
    gstin: [] | [string];
    notes: [] | [string];
} {
    return {
        pan: value.pan ? candid_some(value.pan) : candid_none(),
        name: value.name,
        gstin: value.gstin ? candid_some(value.gstin) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: string;
    subCategory?: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName?: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory?: string;
    assignedName?: string;
}): {
    status: [] | [string];
    subCategory: [] | [string];
    paymentStatus: [] | [string];
    completionDate: [] | [bigint];
    clientName: [] | [string];
    assignmentDate: [] | [bigint];
    bill: [] | [number];
    advanceReceived: [] | [number];
    dueDate: [] | [bigint];
    comment: [] | [string];
    outstandingAmount: [] | [number];
    taskCategory: [] | [string];
    assignedName: [] | [string];
} {
    return {
        status: value.status ? candid_some(value.status) : candid_none(),
        subCategory: value.subCategory ? candid_some(value.subCategory) : candid_none(),
        paymentStatus: value.paymentStatus ? candid_some(value.paymentStatus) : candid_none(),
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        clientName: value.clientName ? candid_some(value.clientName) : candid_none(),
        assignmentDate: value.assignmentDate ? candid_some(value.assignmentDate) : candid_none(),
        bill: value.bill ? candid_some(value.bill) : candid_none(),
        advanceReceived: value.advanceReceived ? candid_some(value.advanceReceived) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        comment: value.comment ? candid_some(value.comment) : candid_none(),
        outstandingAmount: value.outstandingAmount ? candid_some(value.outstandingAmount) : candid_none(),
        taskCategory: value.taskCategory ? candid_some(value.taskCategory) : candid_none(),
        assignedName: value.assignedName ? candid_some(value.assignedName) : candid_none()
    };
}
function to_candid_tuple_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [TaskId, PartialTaskUpdate]): [_TaskId, _PartialTaskUpdate] {
    return [
        value[0],
        to_candid_PartialTaskUpdate_n8(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PartialClientInput>): Array<_PartialClientInput> {
    return value.map((x)=>to_candid_PartialClientInput_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[TaskId, PartialTaskUpdate]>): Array<[_TaskId, _PartialTaskUpdate]> {
    return value.map((x)=>to_candid_tuple_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
