/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaskWithCaptain {
    captainName?: string;
    task: Task;
}
export interface PartialAssigneeInput {
    name: string;
    captain?: string;
}
export interface Task {
    id: TaskId;
    status?: string;
    subCategory: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    createdAt: bigint;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory: string;
    assignedName?: string;
}
export interface PartialTodoInput {
    title: string;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    priority?: bigint;
}
export type TodoId = bigint;
export interface PartialClientInput {
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
}
export interface PartialTaskUpdate {
    id: TaskId;
    status?: string;
    subCategory?: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName?: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory?: string;
    assignedName?: string;
}
export type TaskId = bigint;
export interface Assignee {
    id: AssigneeId;
    name: string;
    captain?: string;
}
export interface Client {
    id: ClientId;
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
    timestamp: bigint;
}
export interface Todo {
    id: TodoId;
    title: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    updatedAt: bigint;
    priority?: bigint;
}
export type ClientId = bigint;
export interface UserProfile {
    name: string;
}
export type AssigneeId = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpdateTasks(updates: Array<PartialTaskUpdate>): Promise<void>;
    createAssignee(assignee: PartialAssigneeInput): Promise<AssigneeId>;
    createClient(client: PartialClientInput): Promise<ClientId>;
    createTask(clientName: string, taskCategory: string, subCategory: string): Promise<TaskId>;
    createTodo(todo: PartialTodoInput): Promise<TodoId>;
    deleteAssignee(assigneeId: AssigneeId): Promise<void>;
    deleteClient(clientId: ClientId): Promise<void>;
    deleteTask(taskId: TaskId): Promise<void>;
    deleteTodo(todoId: TodoId): Promise<void>;
    getAllAssignees(): Promise<Array<Assignee>>;
    getAllClients(): Promise<Array<Client>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllTasksWithCaptain(): Promise<Array<TaskWithCaptain>>;
    getAllTodos(): Promise<Array<Todo>>;
    getAssignee(assigneeId: AssigneeId): Promise<Assignee | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(clientId: ClientId): Promise<Client | null>;
    getTask(taskId: TaskId): Promise<Task | null>;
    getTodo(todoId: TodoId): Promise<Todo | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAssignee(assigneeId: AssigneeId, assignee: PartialAssigneeInput): Promise<void>;
    updateClient(clientId: ClientId, client: PartialClientInput): Promise<void>;
    updateTask(taskId: TaskId, clientName: string, taskCategory: string, subCategory: string, status: string | null, comment: string | null, assignedName: string | null, dueDate: bigint | null, assignmentDate: bigint | null, completionDate: bigint | null, bill: number | null, advanceReceived: number | null, outstandingAmount: number | null, paymentStatus: string | null): Promise<void>;
    updateTodo(todoId: TodoId, todo: PartialTodoInput): Promise<void>;
}
import type { Assignee as _Assignee, AssigneeId as _AssigneeId, Client as _Client, ClientId as _ClientId, PartialAssigneeInput as _PartialAssigneeInput, PartialClientInput as _PartialClientInput, PartialTaskUpdate as _PartialTaskUpdate, PartialTodoInput as _PartialTodoInput, Task as _Task, TaskId as _TaskId, TaskWithCaptain as _TaskWithCaptain, Todo as _Todo, TodoId as _TodoId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpdateTasks(arg0: Array<PartialTaskUpdate>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateTasks(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateTasks(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createAssignee(arg0: PartialAssigneeInput): Promise<AssigneeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignee(to_candid_PartialAssigneeInput_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignee(to_candid_PartialAssigneeInput_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createClient(arg0: PartialClientInput): Promise<ClientId> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(to_candid_PartialClientInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(to_candid_PartialClientInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: string): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2);
            return result;
        }
    }
    async createTodo(arg0: PartialTodoInput): Promise<TodoId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTodo(to_candid_PartialTodoInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTodo(to_candid_PartialTodoInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAssignee(arg0: AssigneeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignee(arg0);
            return result;
        }
    }
    async deleteClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteTodo(arg0: TodoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTodo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTodo(arg0);
            return result;
        }
    }
    async getAllAssignees(): Promise<Array<Assignee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignees();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignees();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasksWithCaptain(): Promise<Array<TaskWithCaptain>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasksWithCaptain();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasksWithCaptain();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTodos(): Promise<Array<Todo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTodos();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTodos();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssignee(arg0: AssigneeId): Promise<Assignee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignee(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignee(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: ClientId): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodo(arg0: TodoId): Promise<Todo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodo(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodo(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAssignee(arg0: AssigneeId, arg1: PartialAssigneeInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssignee(arg0, to_candid_PartialAssigneeInput_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssignee(arg0, to_candid_PartialAssigneeInput_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClient(arg0: ClientId, arg1: PartialClientInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, to_candid_PartialClientInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, to_candid_PartialClientInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string | null, arg6: string | null, arg7: bigint | null, arg8: bigint | null, arg9: bigint | null, arg10: number | null, arg11: number | null, arg12: number | null, arg13: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async updateTodo(arg0: TodoId, arg1: PartialTodoInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTodo(arg0, to_candid_PartialTodoInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTodo(arg0, to_candid_PartialTodoInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Assignee_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignee): Assignee {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TaskWithCaptain_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskWithCaptain): TaskWithCaptain {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Todo_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Todo): Todo {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Assignee]): Assignee | null {
    return value.length === 0 ? null : from_candid_Assignee_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : from_candid_Client_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Todo]): Todo | null {
    return value.length === 0 ? null : from_candid_Todo_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssigneeId;
    name: string;
    captain: [] | [string];
}): {
    id: AssigneeId;
    name: string;
    captain?: string;
} {
    return {
        id: value.id,
        name: value.name,
        captain: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.captain))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClientId;
    pan: [] | [string];
    name: string;
    gstin: [] | [string];
    notes: [] | [string];
    timestamp: bigint;
}): {
    id: ClientId;
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        pan: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.pan)),
        name: value.name,
        gstin: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.gstin)),
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: [] | [string];
    subCategory: string;
    paymentStatus: [] | [string];
    completionDate: [] | [bigint];
    clientName: string;
    assignmentDate: [] | [bigint];
    bill: [] | [number];
    advanceReceived: [] | [number];
    createdAt: bigint;
    dueDate: [] | [bigint];
    comment: [] | [string];
    outstandingAmount: [] | [number];
    taskCategory: string;
    assignedName: [] | [string];
}): {
    id: TaskId;
    status?: string;
    subCategory: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    createdAt: bigint;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory: string;
    assignedName?: string;
} {
    return {
        id: value.id,
        status: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.status)),
        subCategory: value.subCategory,
        paymentStatus: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.paymentStatus)),
        completionDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.completionDate)),
        clientName: value.clientName,
        assignmentDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.assignmentDate)),
        bill: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.bill)),
        advanceReceived: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.advanceReceived)),
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.dueDate)),
        comment: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.comment)),
        outstandingAmount: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.outstandingAmount)),
        taskCategory: value.taskCategory,
        assignedName: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.assignedName))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    captainName: [] | [string];
    task: _Task;
}): {
    captainName?: string;
    task: Task;
} {
    return {
        captainName: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.captainName)),
        task: from_candid_Task_n20(_uploadFile, _downloadFile, value.task)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TodoId;
    title: string;
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: [] | [string];
    updatedAt: bigint;
    priority: [] | [bigint];
}): {
    id: TodoId;
    title: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    updatedAt: bigint;
    priority?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.dueDate)),
        description: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.description)),
        updatedAt: value.updatedAt,
        priority: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.priority))
    };
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignee>): Array<Assignee> {
    return value.map((x)=>from_candid_Assignee_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskWithCaptain>): Array<TaskWithCaptain> {
    return value.map((x)=>from_candid_TaskWithCaptain_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Todo>): Array<Todo> {
    return value.map((x)=>from_candid_Todo_n28(_uploadFile, _downloadFile, x));
}
function to_candid_PartialAssigneeInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialAssigneeInput): _PartialAssigneeInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PartialClientInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialClientInput): _PartialClientInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PartialTaskUpdate_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialTaskUpdate): _PartialTaskUpdate {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_PartialTodoInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialTodoInput): _PartialTodoInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    priority?: bigint;
}): {
    title: string;
    completed: boolean;
    dueDate: [] | [bigint];
    description: [] | [string];
    priority: [] | [bigint];
} {
    return {
        title: value.title,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        priority: value.priority ? candid_some(value.priority) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TaskId;
    status?: string;
    subCategory?: string;
    paymentStatus?: string;
    completionDate?: bigint;
    clientName?: string;
    assignmentDate?: bigint;
    bill?: number;
    advanceReceived?: number;
    dueDate?: bigint;
    comment?: string;
    outstandingAmount?: number;
    taskCategory?: string;
    assignedName?: string;
}): {
    id: _TaskId;
    status: [] | [string];
    subCategory: [] | [string];
    paymentStatus: [] | [string];
    completionDate: [] | [bigint];
    clientName: [] | [string];
    assignmentDate: [] | [bigint];
    bill: [] | [number];
    advanceReceived: [] | [number];
    dueDate: [] | [bigint];
    comment: [] | [string];
    outstandingAmount: [] | [number];
    taskCategory: [] | [string];
    assignedName: [] | [string];
} {
    return {
        id: value.id,
        status: value.status ? candid_some(value.status) : candid_none(),
        subCategory: value.subCategory ? candid_some(value.subCategory) : candid_none(),
        paymentStatus: value.paymentStatus ? candid_some(value.paymentStatus) : candid_none(),
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        clientName: value.clientName ? candid_some(value.clientName) : candid_none(),
        assignmentDate: value.assignmentDate ? candid_some(value.assignmentDate) : candid_none(),
        bill: value.bill ? candid_some(value.bill) : candid_none(),
        advanceReceived: value.advanceReceived ? candid_some(value.advanceReceived) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        comment: value.comment ? candid_some(value.comment) : candid_none(),
        outstandingAmount: value.outstandingAmount ? candid_some(value.outstandingAmount) : candid_none(),
        taskCategory: value.taskCategory ? candid_some(value.taskCategory) : candid_none(),
        assignedName: value.assignedName ? candid_some(value.assignedName) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    captain?: string;
}): {
    name: string;
    captain: [] | [string];
} {
    return {
        name: value.name,
        captain: value.captain ? candid_some(value.captain) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pan?: string;
    name: string;
    gstin?: string;
    notes?: string;
}): {
    pan: [] | [string];
    name: string;
    gstin: [] | [string];
    notes: [] | [string];
} {
    return {
        pan: value.pan ? candid_some(value.pan) : candid_none(),
        name: value.name,
        gstin: value.gstin ? candid_some(value.gstin) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PartialTaskUpdate>): Array<_PartialTaskUpdate> {
    return value.map((x)=>to_candid_PartialTaskUpdate_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
